# Setup
title:               Junho Shin
tagline:             'Computer Vision'
url:                 https://illian01.github.io/
baseurl:             ''
permalink:           pretty


# Custom vars
version:             1.1.0
google_analytics: G-BJ41P0KXFD