# Setup
title:               illian01
tagline:             'All about my study'
description:         'Tech blog'
url:                 https://illian01.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              illian01
  url:               https://illian01.github.io/
  email:             wnsgh578@naver.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
